name: Plugin CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Decrypt keystore
        run: |
          openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEYSTORE_KEY }} -iv ${{ secrets.ENCRYPTED_KEYSTORE_IV }} -in buildKey.jks.enc -out buildKey.jks -d

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Accept Android SDK licenses
        run: yes | /usr/local/lib/android/sdk/tools/bin/sdkmanager --licenses

      - name: Build nodejs plugin debug APK
        uses: gradle/gradle-build-action@v2.4.2
        id: buildNodeJSDebug
        with:
          arguments: :plugin-nodejs:assembleDebug
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build nodejs plugin release APK
        uses: gradle/gradle-build-action@v2.4.2
        id: buildNodeJSRelease
        with:
          arguments: :plugin-nodejs:assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload nodejs plugin debug APK artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() && github.ref == 'refs/heads/master' && steps.buildNodeJSDebug.outcome == 'success' }}
        with:
          name: plugin-nodejs-debug
          path: plugin-nodejs/build/outputs/apk/debug/plugin-nodejs-debug.apk
          if-no-files-found: error

      - name: Upload nodejs plugin release APK artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() && github.ref == 'refs/heads/master' && steps.buildNodeJSRelease.outcome == 'success' }}
        with:
          name: plugin-nodejs-release
          path: plugin-nodejs/build/outputs/apk/release/plugin-nodejs-release.apk
          if-no-files-found: error
